In [1]:
import pandas as pd

In [5]:
products = pd.read_csv('end_to_end/datasets/products_updated.csv')
categories = pd.read_csv('end_to_end/datasets/categories_updated.csv')

In [13]:
categories

                category_name  category_id  margin_percentage
0         Alcoholic Beverages            1              18.11
1           Bakery & Pastries            2              33.67
2   Beverages (Non-Alcoholic)            3              27.76
3         Condiments & Sauces            4              24.16
4                       Dairy            5              12.21
5                      Fruits            6              12.21
6            Grains & Cereals            7               9.57
7              Meat & Poultry            8              31.39
8              Non-Food Items            9              24.23
9              Pantry Staples           10              27.12
10             Prepared Foods           11               8.56
11                    Seafood           12              34.19
12     Snacks & Confectionery           13              30.48
13                      Soups           14              13.73
14        Spices & Seasonings           15              12.91
15                 Vegetables           16              12.95

In [12]:
products = products[['product_id', 'resistant', 'vitality_days', 'category_id', 'cost_price', 'selling_price', 'seasonal_flag', 'demand_score', 'lead_time_days']]

In [8]:
products.head()

,product_id,product_name,resistant,vitality_days,category_id,reorder_levels,stock_quantity,cost_price,selling_price,seasonal_flag,demand_score,category_name,margin_percentage,lead_time_days
0,1,Flour - Whole Wheat,Durable,321,7,400.0,644,8.9,10.6,False,92,Grains & Cereals,9.57,13
1,2,Cookie Chocolate Chip With,Weak,68,2,300.0,2688,22.4,30.6,False,84,Bakery & Pastries,33.67,2
2,3,Onions - Cippolini,Weak,302,16,200.0,4368,17.3,18.8,False,91,Vegetables,12.95,1
3,4,"Sauce - Gravy, Au Jus, Mix",Durable,245,4,250.0,684,14.1,17.3,False,36,Condiments & Sauces,24.16,9
4,5,Artichokes - Jerusalem,Weak,305,16,150.0,2520,3.8,4.0,False,56,Vegetables,12.95,3

In [15]:
products['resistant'].value_counts()

resistant
Durable     192
Weak        134
Moderate     69
Unknown      57
Name: count, dtype: int64